### ISSUE TITLE
Release dates for browsers can be taken from BCD

### ISSUE THREAD

**Issue by romainmenke** [dfabulich/baseline-calculator#2]
see : https://github.com/mdn/browser-compat-data/tree/main/browsers

**Comment by dfabulich** [comment]
Indeed, and that's where I'm getting that data already!

I assume you're filing this issue due to this remark from the README:

> (Strangely, release dates are visible on caniuse.com, but not available in `data.json`. I've filed this as <https://github.com/Fyrd/caniuse/issues/6726>.) 

By that, I only meant that it's annoying that I have to depend on _both_ caniuse _and_ BCD, when I really ought to be able to just depend on caniuse. But, whatever, BCD is right there, and it's fine.

**Comment by romainmenke** [comment]
Ah, I missed that you were already using BCD.

Yeah it doesn't make much sense to me to track the release data in two projects.
We always combine the two data sets when needed :)

**Comment by dfabulich** [comment]
It turns out that `caniuse` _does_ provide release dates, in an undocumented 2.0 version of the JSON. https://github.com/Fyrd/caniuse/blob/main/fulldata-json/data-2.0.json I've filed https://github.com/Fyrd/caniuse/pull/6728 to link to it.

**Comment by romainmenke** [comment]
Nice!
